/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/OkCancelDialog.java to edit this template
 */
package com.josecarlos.supermarket.view.agencies;

import com.josecarlos.supermarket.model.graphs.ComparationMode;
import com.josecarlos.supermarket.model.graphs.Dijkstra;
import com.josecarlos.supermarket.model.graphs.Edge;
import com.josecarlos.supermarket.model.graphs.Graph;
import com.josecarlos.supermarket.model.graphs.Vertex;
import com.josecarlos.supermarket.model.lists.DoubleNode;
import com.josecarlos.supermarket.model.product.Agency;
import com.josecarlos.supermarket.view.listeners.CreateAgencyListener;
import com.josecarlos.supermarket.view.listeners.SelectDestinationListener;
import com.josecarlos.supermarket.view.listeners.SelectVertexListener;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Dimension;
import java.util.List;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author LENOVO
 */
public class AgencyOptions extends javax.swing.JPanel {

    private final CreateAgencyListener listener;
    private SelectDestinationListener listenerVertex;
    private final Vertex vertex;
    private final Graph graph;

    /**
     * Creates new form CreateAgencyDialog
     *
     * @param listener
     */
    public AgencyOptions(CreateAgencyListener listener, Vertex vertex, Graph graph, SelectDestinationListener listenerVertex) {
        initComponents();
        this.listener = listener;

        movementTimeSpinner.setModel(new SpinnerNumberModel(0.0, 0.0, 100.0, 0.1));
        movementTimeSpinner.setEditor(new JSpinner.NumberEditor(movementTimeSpinner, "0.00"));
        enterTimeSpinner.setModel(new SpinnerNumberModel(0.0, 0.0, 100.0, 0.1));
        enterTimeSpinner.setEditor(new JSpinner.NumberEditor(enterTimeSpinner, "0.00"));
        dispatchTimeSpinner.setModel(new SpinnerNumberModel(0.0, 0.0, 100.0, 0.1));
        dispatchTimeSpinner.setEditor(new JSpinner.NumberEditor(dispatchTimeSpinner, "0.00"));
        this.vertex = vertex;
        this.graph = graph;
        this.listenerVertex = listenerVertex;
        loadAgency();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        dispatchTimeSpinner = new javax.swing.JSpinner();
        dispachTimeLabel = new javax.swing.JLabel();
        movementTimeLabel = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        movementTimeSpinner = new javax.swing.JSpinner();
        nameTxt = new javax.swing.JTextField();
        idName = new javax.swing.JLabel();
        idTxt = new javax.swing.JTextField();
        locationLabel = new javax.swing.JLabel();
        locationTxt = new javax.swing.JTextField();
        enterTimeLabel = new javax.swing.JLabel();
        enterTimeSpinner = new javax.swing.JSpinner();
        cancelButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        dispatchTimeSpinner.setToolTipText("Horas");

        dispachTimeLabel.setText("Tiempo de despacho");

        movementTimeLabel.setText("Tiempo de traspaso");

        idLabel.setText("ID");

        movementTimeSpinner.setToolTipText("Horas");

        idName.setText("Nombre");

        idTxt.setEditable(false);

        locationLabel.setText("Ubicación");

        enterTimeLabel.setText("Tiempo de ingreso");

        enterTimeSpinner.setToolTipText("Horas");

        cancelButton.setBackground(new java.awt.Color(255, 0, 0));
        cancelButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelButton.setText("Eliminar");
        cancelButton.addActionListener(this::cancelButtonActionPerformed);

        updateButton.setBackground(new java.awt.Color(0, 153, 204));
        updateButton.setText("Actualizar");
        updateButton.addActionListener(this::updateButtonActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(enterTimeLabel)
                            .addComponent(locationLabel)
                            .addComponent(movementTimeLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(locationTxt)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(enterTimeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(movementTimeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(updateButton)
                                        .addGap(34, 34, 34)
                                        .addComponent(cancelButton))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(dispachTimeLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(dispatchTimeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 61, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(idLabel)
                            .addComponent(idName))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nameTxt)
                            .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(60, 60, 60))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLabel)
                    .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idName)
                    .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(locationLabel)
                    .addComponent(locationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterTimeLabel)
                    .addComponent(enterTimeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dispachTimeLabel)
                    .addComponent(dispatchTimeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(movementTimeLabel)
                    .addComponent(movementTimeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton)
                    .addComponent(updateButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.NORTH);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 566, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 331, Short.MAX_VALUE)
        );

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        listener.onAgencyDeleted(vertex.getAgency());
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void loadAgency() {
        idTxt.setText(vertex.getAgency().getId());
        nameTxt.setText(vertex.getAgency().getName());
        locationTxt.setText(vertex.getAgency().getLocation());
        enterTimeSpinner.setValue(vertex.getAgency().getEnterTime());
        movementTimeSpinner.setValue(vertex.getAgency().getPrepareTime());
        dispatchTimeSpinner.setValue(vertex.getAgency().getDispatchInterval());

        JPanel listPanel = new JPanel();
        listPanel.setLayout(new BoxLayout(listPanel, BoxLayout.Y_AXIS));

        JScrollPane scrollPane = new JScrollPane(listPanel);
        JLabel titles = new JLabel(" --- Destinos por tiempo --- ");
        titles.setMaximumSize(new Dimension(Integer.MAX_VALUE, 20));
        titles.setAlignmentX(Component.CENTER_ALIGNMENT);

        listPanel.add(titles);
        listPanel.add(Box.createRigidArea(new Dimension(0, 5)));

        Dijkstra dijkstra = new Dijkstra();
        List<Vertex> reachableTime = dijkstra.getAllReachableVertices(graph, vertex.getAgency().getKey(), ComparationMode.TIME);
        for (Vertex vertex1 : reachableTime) {
            Agency destination = vertex1.getAgency();
            JButton destinationBtn = new JButton(destination.getName());
            destinationBtn.setMaximumSize(new Dimension(Integer.MAX_VALUE, 15));
            destinationBtn.setAlignmentX(Component.LEFT_ALIGNMENT);

            destinationBtn.addActionListener(e -> {
                listenerVertex.onVertexSelected(vertex1, ComparationMode.TIME);
            });
            
            listPanel.add(destinationBtn);
            listPanel.add(Box.createRigidArea(new Dimension(0, 5)));
        }
        
        JLabel titlePrice = new JLabel(" --- Destinos por costo --- ");
        titlePrice.setMaximumSize(new Dimension(Integer.MAX_VALUE, 20));
        titlePrice.setAlignmentX(Component.CENTER_ALIGNMENT);
        listPanel.add(titlePrice);
        listPanel.add(Box.createRigidArea(new Dimension(0, 5)));
        List<Vertex> reachablePrice = dijkstra.getAllReachableVertices(graph, vertex.getAgency().getKey(), ComparationMode.PRICE);
        for (Vertex vertex1 : reachablePrice) {
            Agency destination = vertex1.getAgency();
            JButton destinationBtn = new JButton(destination.getName());
            destinationBtn.setMaximumSize(new Dimension(Integer.MAX_VALUE, 15));
            destinationBtn.setAlignmentX(Component.LEFT_ALIGNMENT);

            destinationBtn.addActionListener(e -> {
                listenerVertex.onVertexSelected(vertex1, ComparationMode.PRICE);
            });
            
            listPanel.add(destinationBtn);
            listPanel.add(Box.createRigidArea(new Dimension(0, 5)));
        }
        remove(((BorderLayout) getLayout())
                .getLayoutComponent(BorderLayout.CENTER));
        add(scrollPane, BorderLayout.CENTER);
        revalidate();
        repaint();
    }

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        listener.onAgencyDeleted(vertex.getAgency());
        doClose();
    }//GEN-LAST:event_closeDialog

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        double enterTime;
        try {
            enterTime = (double) enterTimeSpinner.getValue();
        } catch (NumberFormatException e) {
            enterTime = 1;
        }
        double dispatchTime;
        try {
            dispatchTime = (double) dispatchTimeSpinner.getValue();
        } catch (NumberFormatException e) {
            dispatchTime = 1;
        }
        double movementTime;
        try {
            movementTime = (double) movementTimeSpinner.getValue();
        } catch (NumberFormatException e) {
            movementTime = 1;
        }
        listener.onAgencyUpdated(new Agency(idTxt.getText(), nameTxt.getText(), locationTxt.getText(), enterTime, movementTime, dispatchTime));
        doClose();
    }//GEN-LAST:event_updateButtonActionPerformed

    private void doClose() {
        setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel dispachTimeLabel;
    private javax.swing.JSpinner dispatchTimeSpinner;
    private javax.swing.JLabel enterTimeLabel;
    private javax.swing.JSpinner enterTimeSpinner;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel idName;
    private javax.swing.JTextField idTxt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel locationLabel;
    private javax.swing.JTextField locationTxt;
    private javax.swing.JLabel movementTimeLabel;
    private javax.swing.JSpinner movementTimeSpinner;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables

}
