/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.josecarlos.supermarket.view.agencies;

import com.josecarlos.supermarket.model.benchmark.BenchmarkResult;
import com.josecarlos.supermarket.model.graphs.ComparationMode;
import com.josecarlos.supermarket.model.graphs.Dijkstra;
import com.josecarlos.supermarket.model.graphs.Edge;
import com.josecarlos.supermarket.model.graphs.Graph;
import com.josecarlos.supermarket.model.graphs.PathResult;
import com.josecarlos.supermarket.model.graphs.Vertex;
import com.josecarlos.supermarket.model.lists.DoubleNode;
import com.josecarlos.supermarket.model.lists.Node;
import com.josecarlos.supermarket.model.lists.SimpleProductsList;
import com.josecarlos.supermarket.model.product.Product;
import com.josecarlos.supermarket.services.Benchmark;
import com.josecarlos.supermarket.services.CSVService;
import com.josecarlos.supermarket.services.MovementService;
import com.josecarlos.supermarket.view.listeners.CreateAgencyListener;
import com.josecarlos.supermarket.view.listeners.ProductsLoaderListener;
import com.josecarlos.supermarket.view.listeners.SelectDestinationListener;
import com.josecarlos.supermarket.view.listeners.SelectVertexListener;
import com.josecarlos.supermarket.view.products.CreateProductDialog;
import com.josecarlos.supermarket.view.products.ProductActionsDialog;
import com.josecarlos.supermarket.view.products.SearchProductDialog;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.io.File;
import java.util.List;
import java.util.Optional;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author LENOVO
 */
public class AgencyView extends javax.swing.JPanel implements ProductsLoaderListener, SelectDestinationListener {

    private Vertex vertex;
    private final CreateAgencyListener listener;
    private final Graph graph;

    /**
     * Creates new form NewJPanel
     *
     * @param vertex
     */
    public AgencyView(Vertex vertex, CreateAgencyListener listener, Graph graph) {
        initComponents();
        this.vertex = vertex;
        this.agencyTitle.setText(vertex.getAgency().getName());
        this.listener = listener;
        this.graph = graph;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        infoPanel = new javax.swing.JPanel();
        titlePanel = new javax.swing.JPanel();
        agencyTitle = new javax.swing.JLabel();
        buttonsPanel = new javax.swing.JPanel();
        searchProduct = new javax.swing.JButton();
        addProduct = new javax.swing.JButton();
        orderByName = new javax.swing.JButton();
        movements = new javax.swing.JButton();
        diagrams = new javax.swing.JButton();
        benchmark = new javax.swing.JButton();
        centerPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        infoPanel.setLayout(new java.awt.BorderLayout());

        agencyTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        agencyTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        agencyTitle.setText("Sucursal");

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(agencyTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 764, Short.MAX_VALUE)
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(agencyTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        infoPanel.add(titlePanel, java.awt.BorderLayout.NORTH);

        searchProduct.setText("Buscar Producto");
        searchProduct.addActionListener(this::searchProductActionPerformed);
        buttonsPanel.add(searchProduct);

        addProduct.setText("Agregar Producto");
        addProduct.addActionListener(this::addProductActionPerformed);
        buttonsPanel.add(addProduct);

        orderByName.setText("Listar por Nombre");
        orderByName.addActionListener(this::orderByNameActionPerformed);
        buttonsPanel.add(orderByName);

        movements.setText("Info y traslados");
        movements.addActionListener(this::movementsActionPerformed);
        buttonsPanel.add(movements);

        diagrams.setText("Generar Diagramas");
        diagrams.addActionListener(this::diagramsActionPerformed);
        buttonsPanel.add(diagrams);

        benchmark.setText("Rendimiento");
        benchmark.addActionListener(this::benchmarkActionPerformed);
        buttonsPanel.add(benchmark);

        infoPanel.add(buttonsPanel, java.awt.BorderLayout.CENTER);

        add(infoPanel, java.awt.BorderLayout.NORTH);

        centerPanel.setLayout(new java.awt.CardLayout());
        add(centerPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void addProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductActionPerformed
        java.awt.EventQueue.invokeLater(() -> {
            CreateProductDialog dialog = new CreateProductDialog(new javax.swing.JFrame(), true, vertex.getAgency().getCatalog());
            dialog.setVisible(true);
        });
    }//GEN-LAST:event_addProductActionPerformed

    private void searchProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchProductActionPerformed
        java.awt.EventQueue.invokeLater(() -> {
            SearchProductDialog dialog = new SearchProductDialog(new javax.swing.JFrame(), true, this, vertex.getAgency().getCatalog());
            dialog.setVisible(true);
        });
    }//GEN-LAST:event_searchProductActionPerformed

    private void movementsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movementsActionPerformed
        AgencyOptions agencyOptions = new AgencyOptions(listener, vertex, graph, this);
        
        remove(((BorderLayout) getLayout())
                .getLayoutComponent(BorderLayout.CENTER));
        add(agencyOptions, BorderLayout.CENTER);
        revalidate();
        repaint();
    }//GEN-LAST:event_movementsActionPerformed

    private void orderByNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderByNameActionPerformed
        onLoadAllProducts();
    }//GEN-LAST:event_orderByNameActionPerformed

    private void diagramsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diagramsActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Seleccione el directorio para guardar");

        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        fileChooser.setAcceptAllFileFilterUsed(false);

        int result = fileChooser.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            String path = selectedFile.getAbsolutePath();

            vertex.getAgency().getCatalog().generateDiagrams(path);
        }
    }//GEN-LAST:event_diagramsActionPerformed

    private void benchmarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_benchmarkActionPerformed
        JPanel listPanel = new JPanel();
        listPanel.setLayout(new BoxLayout(listPanel, BoxLayout.Y_AXIS));

        Benchmark benchmark = new Benchmark();
        List<BenchmarkResult> result = benchmark.runSearchBenchmark(benchmark.getRandomProducts(100, vertex.getAgency().getCatalog()), vertex.getAgency().getCatalog());
        JScrollPane scrollPane = new JScrollPane(listPanel);
        for (BenchmarkResult benchmarkResult : result) {
            
            JLabel productResult = new JLabel(benchmarkResult.toString());

            listPanel.add(productResult);
            listPanel.add(Box.createRigidArea(new Dimension(0, 5)));
        }
        remove(((BorderLayout) getLayout())
                .getLayoutComponent(BorderLayout.CENTER));
        add(scrollPane, BorderLayout.CENTER);
        revalidate();
        repaint();
    }//GEN-LAST:event_benchmarkActionPerformed

    @Override
    public void onProductsLoaded(SimpleProductsList products) {
        JPanel listPanel = new JPanel();
        listPanel.setLayout(new BoxLayout(listPanel, BoxLayout.Y_AXIS));

        JScrollPane scrollPane = new JScrollPane(listPanel);
        Node<Product> head = products.getHead();
        while (head != null) {
            final Product product = head.getValue();
            JButton productBtn = new JButton(head.getValue().getName() + " - $" + head.getValue().getPrice());
            productBtn.setMaximumSize(new Dimension(Integer.MAX_VALUE, 50));
            productBtn.setAlignmentX(Component.CENTER_ALIGNMENT);

            productBtn.addActionListener(e -> {
                handleProductSelection(product);
            });

            listPanel.add(productBtn);
            listPanel.add(Box.createRigidArea(new Dimension(0, 5)));
            head = head.getNext();
        }
        remove(((BorderLayout) getLayout())
                .getLayoutComponent(BorderLayout.CENTER));
        add(scrollPane, BorderLayout.CENTER);
        revalidate();
        repaint();
    }
    
    private void handleProductSelection(Product product) {
        java.awt.EventQueue.invokeLater(() -> {
            ProductActionsDialog dialog = new ProductActionsDialog(new javax.swing.JFrame(), true, vertex.getAgency().getCatalog(), this, product);
            dialog.setVisible(true);
        });
    }

    @Override
    public void onVertexSelected(Vertex agency, ComparationMode mode) {
        Dijkstra dijkstra = new Dijkstra();
        Optional<PathResult> result = dijkstra.shortestPath(graph, vertex.getKey(), agency.getKey(), mode);
        if (result.isPresent()) {
            MovementService movementService = new MovementService(result.get(), agency);
            movementService.run();
        }
    }

    
    @Override
    public void onLoadAllProducts() {
        this.onProductsLoaded(vertex.getAgency().getCatalog().inorder());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addProduct;
    private javax.swing.JLabel agencyTitle;
    private javax.swing.JButton benchmark;
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JButton diagrams;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JButton movements;
    private javax.swing.JButton orderByName;
    private javax.swing.JButton searchProduct;
    private javax.swing.JPanel titlePanel;
    // End of variables declaration//GEN-END:variables
}
