/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.josecarlos.supermarket.view.agencies;

import com.josecarlos.supermarket.model.graphs.Edge;
import com.josecarlos.supermarket.model.graphs.Vertex;
import com.josecarlos.supermarket.model.lists.DoubleNode;
import java.awt.BorderLayout;
import java.awt.GridLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author LENOVO
 */
public class AgencyView extends javax.swing.JPanel {

    private Vertex vertex;

    /**
     * Creates new form NewJPanel
     *
     * @param vertex
     */
    public AgencyView(Vertex vertex) {
        initComponents();
        this.vertex = vertex;
        this.agencyTitle.setText(vertex.getAgency().getName());
        loadEdges();
        this.remove(centerPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        infoPanel = new javax.swing.JPanel();
        titlePanel = new javax.swing.JPanel();
        agencyTitle = new javax.swing.JLabel();
        buttonsPanel = new javax.swing.JPanel();
        searchProduct = new javax.swing.JButton();
        addProduct = new javax.swing.JButton();
        movements = new javax.swing.JButton();
        deleteProduct = new javax.swing.JButton();
        centerPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        infoPanel.setLayout(new java.awt.BorderLayout());

        agencyTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        agencyTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        agencyTitle.setText("Sucursal");

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(agencyTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 871, Short.MAX_VALUE)
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(agencyTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        infoPanel.add(titlePanel, java.awt.BorderLayout.NORTH);

        searchProduct.setText("Buscar Producto");
        searchProduct.addActionListener(this::searchProductActionPerformed);
        buttonsPanel.add(searchProduct);

        addProduct.setText("Agregar Producto");
        addProduct.addActionListener(this::addProductActionPerformed);
        buttonsPanel.add(addProduct);

        movements.setText("Traslados");
        movements.addActionListener(this::movementsActionPerformed);
        buttonsPanel.add(movements);

        deleteProduct.setText("Eliminar Producto");
        buttonsPanel.add(deleteProduct);

        infoPanel.add(buttonsPanel, java.awt.BorderLayout.CENTER);

        add(infoPanel, java.awt.BorderLayout.NORTH);

        javax.swing.GroupLayout centerPanelLayout = new javax.swing.GroupLayout(centerPanel);
        centerPanel.setLayout(centerPanelLayout);
        centerPanelLayout.setHorizontalGroup(
            centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 871, Short.MAX_VALUE)
        );
        centerPanelLayout.setVerticalGroup(
            centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 266, Short.MAX_VALUE)
        );

        add(centerPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void addProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addProductActionPerformed

    private void searchProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchProductActionPerformed

    private void movementsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movementsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_movementsActionPerformed

    private void loadEdges() {
        JPanel panel = new JPanel(new GridLayout(5, 5));
        DoubleNode<Edge<Vertex>> head = vertex.getDestionations().getHead();
        while (head != null) {
            panel.add(new JLabel(head.getValue().getDestination().getAgency().getName()));
            head = head.getNext();
        }
        this.add(panel, BorderLayout.CENTER);
        panel.revalidate();
        panel.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addProduct;
    private javax.swing.JLabel agencyTitle;
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JButton deleteProduct;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JButton movements;
    private javax.swing.JButton searchProduct;
    private javax.swing.JPanel titlePanel;
    // End of variables declaration//GEN-END:variables
}
