package com.josecarlos.supermarket.view.agencies;

import com.josecarlos.supermarket.model.graphs.Graph;
import com.josecarlos.supermarket.model.graphs.Vertex;
import com.josecarlos.supermarket.model.lists.DoubleNode;
import com.josecarlos.supermarket.model.product.Agency;
import javax.swing.JButton;
import com.josecarlos.supermarket.view.listeners.SelectVertexListener;

/**
 *
 * @author LENOVO
 */
public class AgenciesListView extends javax.swing.JPanel {

    private final SelectVertexListener listener;

    /**
     * Creates new form GraphPanel
     *
     * @param graph
     * @param listener
     *
     */
    public AgenciesListView(Graph graph, SelectVertexListener listener) {
        this.listener = listener;
        initComponents();
        DoubleNode<Vertex> head = graph.getAdjacencyList().getHead();
        while (head != null) {
            final Vertex value = head.getValue();
            JButton button = new AgencyButton(value.getAgency());
            button.addActionListener(e -> {
                if (listener != null) {
                    listener.onVertexSelected(value);
                }
            });
            this.add(button);
            head = head.getNext();
        }
        this.revalidate();
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridLayout(20, 10));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
