/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/OkCancelDialog.java to edit this template
 */
package com.josecarlos.supermarket.view.agencies;

import com.josecarlos.supermarket.model.product.Agency;
import com.josecarlos.supermarket.view.listeners.CreateAgencyListener;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JSpinner;
import javax.swing.KeyStroke;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author LENOVO
 */
public class CreateAgencyDialog extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CreateAgencyDialog.class.getName());

    /**
     * A return status code - returned if Cancel button has been pressed
     */
    public static final int RET_CANCEL = 0;
    /**
     * A return status code - returned if OK button has been pressed
     */
    public static final int RET_OK = 1;
    private final CreateAgencyListener listener;

    /**
     * Creates new form CreateAgencyDialog
     *
     * @param parent
     * @param modal
     * @param listener
     */
    public CreateAgencyDialog(java.awt.Frame parent, boolean modal, CreateAgencyListener listener) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.listener = listener;

        movementTimeSpinner.setModel(new SpinnerNumberModel(0.0, 0.0, 100.0, 0.1));
        movementTimeSpinner.setEditor(new JSpinner.NumberEditor(movementTimeSpinner, "0.00"));
        enterTimeSpinner.setModel(new SpinnerNumberModel(0.0, 0.0, 100.0, 0.1));
        enterTimeSpinner.setEditor(new JSpinner.NumberEditor(enterTimeSpinner, "0.00"));
        dispatchTimeSpinner.setModel(new SpinnerNumberModel(0.0, 0.0, 100.0, 0.1));
        dispatchTimeSpinner.setEditor(new JSpinner.NumberEditor(dispatchTimeSpinner, "0.00"));

        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        }); 
    }

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public int getReturnStatus() {
        return returnStatus;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        newAgencyLabel = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        idName = new javax.swing.JLabel();
        idTxt = new javax.swing.JTextField();
        locationLabel = new javax.swing.JLabel();
        locationTxt = new javax.swing.JTextField();
        enterTimeLabel = new javax.swing.JLabel();
        enterTimeSpinner = new javax.swing.JSpinner();
        dispatchTimeSpinner = new javax.swing.JSpinner();
        dispachTimeLabel = new javax.swing.JLabel();
        movementTimeLabel = new javax.swing.JLabel();
        movementTimeSpinner = new javax.swing.JSpinner();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        okButton.setText("OK");
        okButton.addActionListener(this::okButtonActionPerformed);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(this::cancelButtonActionPerformed);

        newAgencyLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        newAgencyLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newAgencyLabel.setText("Nueva Sucursal");

        idLabel.setText("ID");

        idName.setText("Nombre");

        locationLabel.setText("Ubicación");

        enterTimeLabel.setText("Tiempo de ingreso");

        enterTimeSpinner.setToolTipText("Horas");

        dispatchTimeSpinner.setToolTipText("Horas");

        dispachTimeLabel.setText("Tiempo de despacho");

        movementTimeLabel.setText("Tiempo de traspaso");

        movementTimeSpinner.setToolTipText("Horas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelButton)
                .addContainerGap())
            .addComponent(newAgencyLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(enterTimeLabel)
                            .addComponent(locationLabel)
                            .addComponent(movementTimeLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(enterTimeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                                .addComponent(dispachTimeLabel)
                                .addGap(18, 18, 18)
                                .addComponent(dispatchTimeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(locationTxt)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(movementTimeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(idLabel)
                            .addComponent(idName))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                            .addComponent(idTxt))))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelButton, okButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(newAgencyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLabel)
                    .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idName)
                    .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(locationLabel)
                    .addComponent(locationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterTimeLabel)
                    .addComponent(enterTimeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dispachTimeLabel)
                    .addComponent(dispatchTimeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(movementTimeLabel)
                    .addComponent(movementTimeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(okButton))
                .addContainerGap())
        );

        getRootPane().setDefaultButton(okButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        double enterTime;
        try {
            enterTime = (double) enterTimeSpinner.getValue();
        } catch (NumberFormatException e) {
            enterTime = 1;
        }
        double dispatchTime;
        try {
            dispatchTime = (double) dispatchTimeSpinner.getValue();
        } catch (NumberFormatException e) {
            dispatchTime = 1;
        }
        double movementTime;
        try {
            movementTime = (double) movementTimeSpinner.getValue();
        } catch (NumberFormatException e) {
            movementTime = 1;
        }
        listener.onAgencyCreated(new Agency(idTxt.getText(), nameTxt.getText(), locationTxt.getText(), enterTime, movementTime, dispatchTime));
        doClose(RET_OK);
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel dispachTimeLabel;
    private javax.swing.JSpinner dispatchTimeSpinner;
    private javax.swing.JLabel enterTimeLabel;
    private javax.swing.JSpinner enterTimeSpinner;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel idName;
    private javax.swing.JTextField idTxt;
    private javax.swing.JLabel locationLabel;
    private javax.swing.JTextField locationTxt;
    private javax.swing.JLabel movementTimeLabel;
    private javax.swing.JSpinner movementTimeSpinner;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JLabel newAgencyLabel;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables

    private int returnStatus = RET_CANCEL;
}
