package com.josecarlos.supermarket.view;

import com.josecarlos.supermarket.model.graphs.Graph;
import com.josecarlos.supermarket.model.graphs.Vertex;
import com.josecarlos.supermarket.model.product.Agency;
import com.josecarlos.supermarket.view.agencies.AgenciesListView;
import com.josecarlos.supermarket.view.agencies.AgencyView;
import com.josecarlos.supermarket.view.agencies.CreateAgencyDialog;
import com.josecarlos.supermarket.view.listeners.CreateAgencyListener;
import java.awt.BorderLayout;
import javax.swing.JDialog;
import javax.swing.JFrame;
import com.josecarlos.supermarket.view.listeners.SelectVertexListener;

/**
 *
 * @author LENOVO
 */
public class MainScreen extends javax.swing.JFrame implements SelectVertexListener, CreateAgencyListener {

    private Graph agencies;

    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        this.agencies = new Graph();
        initComponents();
        this.setLocationRelativeTo(null);
        Agency a1 = new Agency("12431f", "sucursal-1", "xela", "3", "3", "34");
        Agency a2 = new Agency("124gf3", "sucursal-2", "toto", "5", "5", "44");
        Agency a3 = new Agency("qwgwq", "sucursal-3", "huehue", "9", "12", "23");
        Agency a4 = new Agency("f2f", "sucursal-4", "cocales", "56", "14", "8");
        agencies.addEdge(a1, a3, 15, 6);
        agencies.addEdge(a3, a2, 9, 2);
        agencies.addEdge(a2, a1, 12, 5);
        agencies.addVertex(a4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        agenciesMenu = new javax.swing.JMenu();
        selectAgencyMenu = new javax.swing.JMenuItem();
        createAgencyMenu = new javax.swing.JMenuItem();
        moveMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 800));

        fileMenu.setText("Archivos");
        menuBar.add(fileMenu);

        agenciesMenu.setText("Sucursales");

        selectAgencyMenu.setText("Seleccionar");
        selectAgencyMenu.addActionListener(this::selectAgencyMenuActionPerformed);
        agenciesMenu.add(selectAgencyMenu);

        createAgencyMenu.setText("Agregar");
        createAgencyMenu.addActionListener(this::createAgencyMenuActionPerformed);
        agenciesMenu.add(createAgencyMenu);

        menuBar.add(agenciesMenu);

        moveMenu.setText("Traslado");
        menuBar.add(moveMenu);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectAgencyMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectAgencyMenuActionPerformed
        AgenciesListView graphPanel = new AgenciesListView(agencies, this);
        this.getContentPane().removeAll();
        this.add(graphPanel, BorderLayout.CENTER);
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_selectAgencyMenuActionPerformed

    private void createAgencyMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAgencyMenuActionPerformed
        java.awt.EventQueue.invokeLater(() -> {
            CreateAgencyDialog dialog = new CreateAgencyDialog(new javax.swing.JFrame(), true, this);
            dialog.setVisible(true);
        });
    }//GEN-LAST:event_createAgencyMenuActionPerformed

    @Override
    public void onVertexSelected(Vertex agency) {
        this.getContentPane().removeAll();
        this.add(new AgencyView(agency), BorderLayout.CENTER);
        this.revalidate();
        this.repaint();
    }

    @Override
    public void onAgencyCreated(Agency agency) {
        if (this.agencies.exists(agency)) {
            java.awt.EventQueue.invokeLater(() -> {
                JDialog dialog = new JDialog(new JFrame(), "Ya existe una agencia con el mismo código");
                dialog.setVisible(true);
            });
            return;
        }
        this.agencies.addVertex(agency);
        this.getContentPane().removeAll();
        this.add(new AgenciesListView(agencies, this), BorderLayout.CENTER);
        this.revalidate();
        this.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu agenciesMenu;
    private javax.swing.JMenuItem createAgencyMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu moveMenu;
    private javax.swing.JMenuItem selectAgencyMenu;
    // End of variables declaration//GEN-END:variables
}
