/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/OkCancelDialog.java to edit this template
 */
package com.josecarlos.supermarket.view.products;

import com.josecarlos.supermarket.model.product.Product;
import com.josecarlos.supermarket.view.listeners.ProductListener;
import com.josecarlos.supermarket.view.listeners.ProductsLoaderListener;
import com.josecarlos.supermarket.view.shared.WarningDialog;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JSpinner;
import javax.swing.KeyStroke;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author LENOVO
 */
public class ProductActionsDialog extends javax.swing.JDialog {

    private final ProductListener listener;
    private final ProductsLoaderListener listenerLoader;
    private final Product product;

    /**
     * Creates new form CreateAgencyDialog
     *
     * @param parent
     * @param modal
     * @param listener
     * @param listenerLoader
     * @param product
     */
    public ProductActionsDialog(java.awt.Frame parent, boolean modal, ProductListener listener, ProductsLoaderListener listenerLoader, Product product) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.listener = listener;
        this.product = product;
        this.listenerLoader = listenerLoader;

        priceSpinner.setModel(new SpinnerNumberModel(0.0, 0.0, null, 0.1));
        priceSpinner.setEditor(new JSpinner.NumberEditor(priceSpinner, "0.00"));

        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                doClose();
            }
        });
        loadProduct();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deleteButton = new javax.swing.JButton();
        newProductLabel = new javax.swing.JLabel();
        barcodeLabel = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        barcodeTxt = new javax.swing.JTextField();
        categoryLabel = new javax.swing.JLabel();
        categoryTxt = new javax.swing.JTextField();
        dateSpinner = new javax.swing.JSpinner();
        dateLabel = new javax.swing.JLabel();
        brandTxt = new javax.swing.JTextField();
        brandLabel = new javax.swing.JLabel();
        stockLabel = new javax.swing.JLabel();
        stockSpinner = new javax.swing.JSpinner();
        priceLabel = new javax.swing.JLabel();
        priceSpinner = new javax.swing.JSpinner();
        updateButton = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        deleteButton.setBackground(new java.awt.Color(255, 0, 0));
        deleteButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteButton.setText("Eliminar");
        deleteButton.addActionListener(this::deleteButtonActionPerformed);

        newProductLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        newProductLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newProductLabel.setText("Producto");

        barcodeLabel.setText("Código de barras");

        nameLabel.setText("Nombre");

        barcodeTxt.setEditable(false);

        categoryLabel.setText("Categoría");

        dateSpinner.setModel(new javax.swing.SpinnerDateModel());
        dateSpinner.setToolTipText("Año");
        dateSpinner.setEditor(new javax.swing.JSpinner.DateEditor(dateSpinner, "dd MMMM yyyy"));

        dateLabel.setText("Fecha de expiración");

        brandLabel.setText("Marca");

        stockLabel.setText("Stock");

        stockSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        stockSpinner.setToolTipText("Año");
        stockSpinner.setEditor(new javax.swing.JSpinner.NumberEditor(stockSpinner, ""));

        priceLabel.setText("Precio");

        priceSpinner.setModel(new javax.swing.SpinnerNumberModel());
        priceSpinner.setToolTipText("Año");
        priceSpinner.setEditor(new javax.swing.JSpinner.NumberEditor(priceSpinner, ""));

        updateButton.setText("Actualizar");
        updateButton.addActionListener(this::updateButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(newProductLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(categoryLabel)
                            .addComponent(barcodeLabel))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(priceLabel)
                            .addComponent(brandLabel))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(categoryTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(barcodeTxt)
                    .addComponent(brandTxt, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(priceSpinner, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dateLabel)
                                .addGap(18, 18, 18)
                                .addComponent(dateSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nameLabel)
                                .addGap(18, 18, 18)
                                .addComponent(nameTxt)))
                        .addGap(95, 95, 95))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(stockLabel)
                        .addGap(18, 18, 18)
                        .addComponent(stockSpinner)
                        .addGap(170, 170, 170))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(updateButton)
                        .addGap(18, 18, 18)
                        .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(newProductLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(barcodeLabel)
                    .addComponent(barcodeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabel)
                    .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoryLabel)
                    .addComponent(categoryTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateLabel)
                    .addComponent(dateSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brandTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(brandLabel)
                    .addComponent(stockLabel)
                    .addComponent(stockSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceLabel)
                    .addComponent(priceSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateButton)
                    .addComponent(deleteButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getRootPane().setDefaultButton(deleteButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        WarningDialog dialog;
        dialog = new WarningDialog(new javax.swing.JFrame(), true, "Advertencia", "¿Esta seguro que desea eliminar el producto?");
        dialog.setVisible(true);

        if (dialog.getReturnStatus() == WarningDialog.RET_OK) {
            listener.onProductDeleted(product);
            listenerLoader.onLoadAllProducts();
            doClose();
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose();
    }//GEN-LAST:event_closeDialog

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        if (barcodeTxt.getText().isBlank()) {
            return;
        }
        double price;
        try {
            price = (double) priceSpinner.getValue();
        } catch (NumberFormatException e) {
            price = 0;
        }
        int stock;
        try {
            stock = (int) stockSpinner.getValue();
        } catch (NumberFormatException e) {
            stock = 0;
        }
        Date dateValue = (Date) dateSpinner.getValue();
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
        String formattedValue = format.format(dateValue);
        listener.onProductModified(
                product,
                new Product(nameTxt.getText(), barcodeTxt.getText(), categoryTxt.getText(), formattedValue, brandTxt.getText(), price, stock)
        );
        listenerLoader.onLoadAllProducts();
        doClose();
    }//GEN-LAST:event_updateButtonActionPerformed

    private void doClose() {
        setVisible(false);
        dispose();
    }

    private void loadProduct() {
        barcodeTxt.setText(product.getBarcode());
        brandTxt.setText(product.getBrand());
        categoryTxt.setText(product.getCategory());
        LocalDate date = LocalDate.parse(product.getExpireDate(), DateTimeFormatter.ofPattern("yyyy-MM-dd"));
        dateSpinner.setValue(Date.from(date.atStartOfDay(ZoneId.systemDefault()).toInstant()));
        nameTxt.setText(product.getName());
        priceSpinner.setValue(product.getPrice());
        stockSpinner.setValue(product.getStock());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel barcodeLabel;
    private javax.swing.JTextField barcodeTxt;
    private javax.swing.JLabel brandLabel;
    private javax.swing.JTextField brandTxt;
    private javax.swing.JLabel categoryLabel;
    private javax.swing.JTextField categoryTxt;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JSpinner dateSpinner;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JLabel newProductLabel;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JSpinner priceSpinner;
    private javax.swing.JLabel stockLabel;
    private javax.swing.JSpinner stockSpinner;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables

}
