/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/OkCancelDialog.java to edit this template
 */
package com.josecarlos.supermarket.view.products;

import com.josecarlos.supermarket.model.lists.SimpleProductsList;
import com.josecarlos.supermarket.view.agencies.*;
import com.josecarlos.supermarket.model.product.Agency;
import com.josecarlos.supermarket.model.product.Product;
import com.josecarlos.supermarket.view.listeners.CreateAgencyListener;
import com.josecarlos.supermarket.view.listeners.ProductListener;
import com.josecarlos.supermarket.view.listeners.ProductsLoaderListener;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JSpinner;
import javax.swing.KeyStroke;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author LENOVO
 */
public class SearchProductDialog extends javax.swing.JDialog {

    /**
     * A return status code - returned if Cancel button has been pressed
     */
    public static final int RET_CANCEL = 0;
    public static final String[] SEARCH_OPTIONS = new String[]{"Código de Barras", "Nombre", "Categoria", "Por rango de fechas"};
    /**
     * A return status code - returned if OK button has been pressed
     */
    public static final int RET_OK = 1;
    private final ProductsLoaderListener listener;
    private final ProductListener listenerProducts;

    /**
     * Creates new form CreateAgencyDialog
     *
     * @param parent
     * @param modal
     * @param listener
     */
    public SearchProductDialog(java.awt.Frame parent, boolean modal, ProductsLoaderListener listener, ProductListener listenerProducts) {
        super(parent, modal);
        initComponents();
        this.datePanel.setVisible(false);
        this.setLocationRelativeTo(null);
        this.listener = listener;
        this.listenerProducts = listenerProducts;

        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });
    }

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public int getReturnStatus() {
        return returnStatus;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        searchProductLabel = new javax.swing.JLabel();
        searchOptionsCombo = new javax.swing.JComboBox<>();
        labelSearchFor = new javax.swing.JLabel();
        searchText = new javax.swing.JTextField();
        datePanel = new javax.swing.JPanel();
        startDateSpinner = new javax.swing.JSpinner();
        endDateSpinner = new javax.swing.JSpinner();
        startLabel = new javax.swing.JLabel();
        endLabel = new javax.swing.JLabel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        okButton.setText("OK");
        okButton.addActionListener(this::okButtonActionPerformed);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(this::cancelButtonActionPerformed);

        searchProductLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        searchProductLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        searchProductLabel.setText("Buscar Productos");

        searchOptionsCombo.setModel(new javax.swing.DefaultComboBoxModel<>(SEARCH_OPTIONS));
        searchOptionsCombo.addActionListener(this::searchOptionsComboActionPerformed);

        labelSearchFor.setText("Buscar por");

        searchText.addActionListener(this::searchTextActionPerformed);

        startDateSpinner.setModel(new javax.swing.SpinnerDateModel());
        startDateSpinner.setEditor(new javax.swing.JSpinner.DateEditor(startDateSpinner, "dd MMMM yyyy"));

        endDateSpinner.setModel(new javax.swing.SpinnerDateModel());
        endDateSpinner.setEditor(new javax.swing.JSpinner.DateEditor(endDateSpinner, "dd MMMM yyyy"));

        startLabel.setText("Fecha de inicio");

        endLabel.setText("Fecha de fin");

        javax.swing.GroupLayout datePanelLayout = new javax.swing.GroupLayout(datePanel);
        datePanel.setLayout(datePanelLayout);
        datePanelLayout.setHorizontalGroup(
            datePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, datePanelLayout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(startLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(190, 190, 190)
                .addComponent(endLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(159, 159, 159))
            .addGroup(datePanelLayout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(startDateSpinner)
                .addGap(164, 164, 164)
                .addComponent(endDateSpinner)
                .addGap(136, 136, 136))
        );
        datePanelLayout.setVerticalGroup(
            datePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, datePanelLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(datePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startLabel)
                    .addComponent(endLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(datePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startDateSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(endDateSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(searchProductLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelSearchFor)
                        .addGap(18, 18, 18)
                        .addComponent(searchOptionsCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchText))
                    .addComponent(datePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelButton, okButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(searchProductLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSearchFor)
                    .addComponent(searchOptionsCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(datePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(okButton))
                .addContainerGap())
        );

        getRootPane().setDefaultButton(okButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        switch (searchOptionsCombo.getSelectedIndex()) {
            case 0 ->
                listener.onProductsLoaded(listenerProducts.searchProduct(searchText.getText()));
            case 1 ->
                listener.onProductsLoaded(listenerProducts.searchByName(searchText.getText()));
            case 2 ->
                listener.onProductsLoaded(listenerProducts.searchByCategory(searchText.getText()));
            case 3 -> {
                Date startValue = (Date) startDateSpinner.getValue();
                Date endValue = (Date) endDateSpinner.getValue();
                SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
                listener.onProductsLoaded(listenerProducts.searchByDate(format.format(startValue), format.format(endValue)));
            }
            default ->
                listener.onProductsLoaded(new SimpleProductsList());
        }
        doClose(RET_OK);
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void searchOptionsComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchOptionsComboActionPerformed
        // TODO add your handling code here:
        if (searchOptionsCombo.getSelectedIndex() == 3) {
            this.datePanel.setVisible(true);
        } else {
            this.datePanel.setVisible(false);
        }
    }//GEN-LAST:event_searchOptionsComboActionPerformed

    private void searchTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTextActionPerformed

    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel datePanel;
    private javax.swing.JSpinner endDateSpinner;
    private javax.swing.JLabel endLabel;
    private javax.swing.JLabel labelSearchFor;
    private javax.swing.JButton okButton;
    private javax.swing.JComboBox<String> searchOptionsCombo;
    private javax.swing.JLabel searchProductLabel;
    private javax.swing.JTextField searchText;
    private javax.swing.JSpinner startDateSpinner;
    private javax.swing.JLabel startLabel;
    // End of variables declaration//GEN-END:variables

    private int returnStatus = RET_CANCEL;
}
